### ISSUE TITLE
Verify `pylint` behaviour for `umpost`

### ISSUE THREAD

**Issue by truth-quark** [ACCESS-NRI/um2nc-standalone#79]
During the #74 review, it was unclear if the linter workflow step was skipped the `umpost.um2netcdf` module due to the `--ignored-modules` option in `.github/workflows/CI.yml`:
```YAML
      - name: Lint
        shell: bash -l {0}
        run: pylint --extension-pkg-whitelist=netCDF4 --ignored-modules=um2netcdf4,umpost -E umpost
```
There is potential that modules in the `umpost` package are skipped, in addition to `um2netcdf4`. Given the mid-August release, this was not confirmed due to lack of time.

The main task is ensuring that `umpost` modules are linted.
Note: this should happen after #78 to remove old `um2netcdf4` imports.
