### ISSUE TITLE
Which `bash` runner to use for entry point CI tests?

### ISSUE THREAD

**Issue by truth-quark** [ACCESS-NRI/um2nc-standalone#87]
From #86, there's a suggestion regarding which `bash` test runner to use for `um2nc` entrypoints:

https://github.com/ACCESS-NRI/um2nc-standalone/blob/82/un2nc-ci-entry-test/.github/workflows/CI.yml#L96-L102

```YAML
  - name: Entrypoint test of driver script
    shell: bash -l {0}
    run: esm1p5_convert_nc --help

  - name: Entrypoint test of um2netcdf script
    shell: bash -l {0}
    run: um2nc --help
```
@CodeGat  suggested removing `shell: bash -l {0}` lines to use the default `bash --noprofile --norc -eo pipefail {0}` provided by GitHub. See https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell. It is not clear if this works with `conda` environments required for testing (part of the reason for using `bash -l`.

The first step in this task is testing if the GitHub default `bash` command works with `conda`.
